include: package:leancode_lint/analysis_options.yaml

plugins:
  leancode_lint:
    git:
      url: https://github.com/leancodepl/flutter_corelibrary
      path: packages/leancode_lint
      ref: migrate-lints-to-analysis-server-plugin

analyzer:
  exclude:
    - '**.g.dart'

leancode_lint:
  application_prefix: App
